---
- hosts: services
  roles:
    - { role: ccie-roles/replicated }
  vars:
    replicated_cli: 'replicated'
    replicated_install_params: 'local-address="{{ services_ip }}" no-proxy'
    replicated_license_file_path: "{{ license_file_path | default('') }}"
    replicated_app_settings:
      hostname:
        value: "{{ services_hostname | default(services_ip) }}"
      allow_cluster:
        value: 1
      secret_passphrase:
        value: "{{ secret_passphrase }}"
      ghe_type:
        value: "{{ ghe_type | default(replicated_default_app_settings.ghe_type.value) }}"
      ghe_domain:
        value: "{{ ghe_domain | default('') }}"
      ghe_client_id:
        value: "{{ github_client_id | default('') }}"
      ghe_client_secret:
        value: "{{ github_client_secret | default('') }}"
      iam_auth_type:
        value: "user"
      aws_region:
        value: "{{ aws_region }}"
      aws_access_key_id:
        value: "{{ aws_access_key_id }}"
      aws_secret_access_key:
        value: "{{ aws_access_secret_key }}"
      cloudwatch_enabled:
        value: "0"
      s3_bucket:
        value: "{{ s3_bucket }}"
      storage_backend:
        value: "storage_backend_s3"
      sqs_queue_url:
        value: "{{ sqs_queue_url }}"
